### ISSUE TITLE
Can't set Client for Checksum

### ISSUE THREAD

**Issue by juliussohn** [paymill/paymill-php#106]
When I create a checksum for Paypal checkout, I can't set a Client ID. A new Client is created with every checkout.

**Comment by rathesDot** [comment]
Having the same problem. Did you find a solution @juliussohn?

**Comment by cyrrill** [comment]
This is fixed in #118, however the last release here was 4 months ago. So if you need these fixes short term feel free to use:  https://github.com/cyrrill/paymill-php  I will be maintaining that fork the foreseeable future.

**Comment by rathesDot** [comment]
Hey @cyrrill: That's what I have done! Thank you very much!

**Comment by alexsegura** [comment]
Same problem here, the `client` parameter is definitely missing. 

@mschindler83 are you the maintainer of this project?

**Comment by mschindler83** [comment]
@alexsegura yes I'm one of the maintainers.
PR #118 fixed this issue a few days ago.
Thank you for reporting.

**Comment by alexsegura** [comment]
:+1:
