### ISSUE TITLE
Paypal Payment Holder && Account is mssing

### ISSUE THREAD

**Issue by elsweppo** [paymill/paymill-php#122]
Could you please update the function createPayment in the class Services/ResponseHandler? 

    private function _createPayment($response)
    {
        $model = new Models\Payment();
        $model->setId($response['id']);
        $model->setType($response['type']);
        $model->setClient($this->_convertResponseToModel($response['client'], "client"));
		echo $response['type'];
        if ($response['type'] === "creditcard") {
            $model->setCardType($response['card_type']);
            $model->setCountry($response['country']);
            $model->setExpireMonth($response['expire_month']);
            $model->setExpireYear($response['expire_year']);
            $model->setCardHolder($response['card_holder']);
            $model->setLastFour($response['last4']);
        } else if ($response['type'] === "debit") {
            $model->setHolder($response['holder']);
            $model->setCode($response['code']);
            $model->setAccount($response['account']);
            $model->setBic($response['bic']);
            $model->setIban($response['iban']);
        } else if ($response['type'] == 'paypal'){
        	echo "paypal creation";
        	$model->setAccount($response['account']);
			$model->setHolder($response['holder']);
        }
        $model->setCreatedAt($response['created_at']);
        $model->setUpdatedAt($response['updated_at']);
        $model->setAppId($response['app_id']);
        return $model;
    }

**Comment by Iarwa1n** [comment]
HI @elsweppo ,

thanks for the contribution but could you provide a pull request for this change, please? 
The "echo" line probably should not be part of this then.

**Comment by mschindler83** [comment]
This has been merged with PR #117
