### ISSUE TITLE
ERROR: SSL23_GET_SERVER_HELLO:tlsv1 unrecognized name

### ISSUE THREAD

**Issue by wittfabian** [paymill/paymill-php#135]
I received the following error 

> Paymill\Services\PaymillException: error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 unrecognized name

Caused by

```
$request = new Paymill\Request( 'PAYMILL_PRIVATE_KEY' );
$client = new Paymill\Models\Request\Client();
$client->setId('CLIENT_ID');
```

Can someone explain the error?

**Comment by tschelabaumann** [comment]
Looks like your client is too old, can you please please post the output of curl_version()?

**Comment by wittfabian** [comment]
Hi,
it is an Google App Engine with PHP.

Output of curl_version():

```
{
  "version_number": 469504,
  "age": 3,
  "features": 557589,
  "ssl_version_number": 0,
  "version": "7.42.0",
  "host": "x86_64-pc-nacl",
  "ssl_version": "OpenSSL/1.0.2h",
  "libz_version": "",
  "protocols": [
    "dict",
    "file",
    "ftp",
    "ftps",
    "gopher",
    "http",
    "https",
    "imap",
    "imaps",
    "pop3",
    "pop3s",
    "rtsp",
    "smb",
    "smbs",
    "smtp",
    "smtps",
    "telnet",
    "tftp"
  ]
}
```

**Comment by wittfabian** [comment]
With the "google_app_engine.enable_curl_lite" version, described in the link, I receive the following error:

`StatusCode: 401 / ErrorMessage: Access Denied`

**Comment by tschelabaumann** [comment]
This seems not to be a problem with the library itself then.
Regarding the Access Denied it looks like you are using the wrong key. Sometimes private and public key are mixed up.
