### ISSUE TITLE
Bug in ```getOne``` method ?

### ISSUE THREAD

**Issue by jdeniau** [paymill/paymill-php#69]
Hi,

I try to use the `getOne`  method as this:

``` php
$apiKey = '..............';
$request = new \Paymill\Request($apiKey);
$transaction = new \Paymill\Models\Request\Transaction;
$response = $request->getOne($transaction);                       
```

But I got this error:

``` sh
PHP Notice:  Undefined index: id in /home/j_deniau/code/website/vendor/paymill/paymill/lib/Paymill/Services/ResponseHandler.php on line 177
PHP Stack trace:
PHP   1. {main}() php shell code:0
PHP   2. Paymill\Request->getOne() php shell code:1
PHP   3. Paymill\Request->_request() /home/j_deniau/code/website/vendor/paymill/paymill/lib/Paymill/Request.php:101
PHP   4. Paymill\Services\ResponseHandler->convertResponse() /home/j_deniau/code/website/vendor/paymill/paymill/lib/Paymill/Request.php:168
PHP   5. Paymill\Services\ResponseHandler->_convertResponseToModel() /home/j_deniau/code/website/vendor/paymill/paymill/lib/Paymill/Services/ResponseHandler.php:65
PHP   6. Paymill\Services\ResponseHandler->_createTransaction() /home/j_deniau/code/website/vendor/paymill/paymill/lib/Paymill/Services/ResponseHandler.php:93
PHP Notice:  Undefined index: amount in /home/j_deniau/code/website/vendor/paymill/paymill/lib/Paymill/Services/ResponseHandler.php on line 178
PHP Stack trace:
PHP   1. {main}() php shell code:0

................
```

As far as I debugged the code, I found that the executed code is [this one](https://github.com/paymill/paymill-php/blob/master/lib/Paymill/Request.php#L223) and  the `$response['body']['data']` object is an array containing only one entry (because we used the `getOne` function). So the [convert method](https://github.com/paymill/paymill-php/blob/master/lib/Paymill/Services/ResponseHandler.php#L176) do not know how to work with an array of array.

If I use the `getAll` function, then it does not try to convert the response body and return an array (instead of objects).

Thank you.

**Comment by Bouzidimaha** [comment]
Hi 
Can someone tell me how to create a checksum for Paypal! I need to integrate paypal in paymill .
Any help please! thanks
